FROM python:3.9-slim

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        zlib1g-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libwebp-dev \
        liblcms2-dev \
        tcl-dev \
        tk-dev \
        freetype*
        libfreetype6-dev \
        libjpeg-turbo8-dev

RUN pip install --no-cache-dir -r requirements.txt

RUN python manage.py collectstatic --noinput


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
